monolog:
  handlers:
    signaling:
      type: stream
      path: "%kernel.logs_dir%/signaling.log"
      level: info
      channels: ["signaling"]
    email:
      type: stream
      path: "%kernel.logs_dir%/email.log"
      level: info
      channels: ["email"]